export const en = {
  "language.selectorLabel": "Change language",
  "language.title": "Choose language",
  "language.english": "English",
  "language.arabic": "العربية",
  "language.french": "Français",
  "language.romanian": "Română",
  "common.back": "Back",
  "common.close": "Close",
  "common.clear": "Clear",
  "common.retry": "Try again",
  "common.loading": "Loading…",
  "common.optional": "optional",
  "common.free": "Free",
  "common.home": "Home",
  "common.shop": "Shop",
  "common.account": "Account",
  "common.categories": "Categories",
  "common.menu": "Menu",
  "common.viewAll": "View all",
  "common.seeAll": "See all",
  "common.shopNow": "Shop now",
  "navigation.home": "Home",
  "navigation.shop": "Shop",
  "navigation.cart": "Cart",
  "navigation.notifications": "Notifications",
  "navigation.account": "Account",
  "navigation.cartAccessibility": "Cart, {count} items",
  "navigation.notificationsAccessibility": "Notifications, {count} unread",
  "navigation.openMenu": "Open shop menu",
  "navigation.closeMenu": "Close menu",
  "navigation.search": "Search products",
  "navigation.wishlist": "Open wishlist",
  "navigation.shoppingBag": "Open shopping bag, {count} items",
  "navigation.currency": "Currency is {currency}. Switch currency",
  "navigation.whatsapp": "Chat with customer service on WhatsApp",
  "home.shopByAge": "Shop by Age",
  "home.shopByAgeSubtitle": "Choose the right age range",
  "home.topPicks": "Top Picks For You",
  "home.topPicksSubtitle": "Fresh styles parents love",
  "home.shopByCategory": "Shop by Category",
  "home.shopByCategorySubtitle": "Curated outfits, essentials & favorites",
  "home.exploreStyles": "Explore Styles",
  "home.exploreStylesSubtitle": "Made for every little moment",
  "home.tinyEssentials": "Tiny Essentials",
  "home.tinyEssentialsSubtitle": "Everyday softness for newborn days",
  "home.ourBrands": "Our Brands",
  "home.ourBrandsSubtitle": "Labels families know and love",
  "home.latestCollection": "Latest Collection",
  "home.latestCollectionSubtitle": "New-season favorites",
  "home.cartersPick": "Carter's pick",
  "home.shopifyPicks": "Shopify picks",
  "home.babyAndKids": "Baby & kids",
  "home.updating": "Updating storefront content…",
  "home.unableToLoad": "Unable to load the homepage.",
  "home.collection": "Collection",
  "home.allProducts": "All Products",
  "home.specialPrices": "Special Prices",
  "home.featuredCategory": "Featured category",
  "home.shopCategory": "Shop category",
  "home.categoryComfort": "Easy matching looks made for everyday comfort.",
  "collection.products": "{count} PRODUCTS",
  "collection.filterSort": "FILTER & SORT",
  "collection.loading": "Loading products…",
  "collection.loadError": "Unable to load this collection right now.",
  "collection.empty": "No products found in this collection.",
  "collection.availability": "Availability",
  "collection.allProducts": "All products",
  "collection.inStock": "In stock",
  "collection.priceRange": "Price range",
  "collection.minimum": "Min",
  "collection.maximum": "Max",
  "collection.brand": "Brand",
  "collection.size": "Size",
  "collection.sortBy": "Sort by",
  "collection.featured": "Featured",
  "collection.priceLow": "Price: low to high",
  "collection.priceHigh": "Price: high to low",
  "collection.nameAz": "Name: A–Z",
  "collection.showCount": "Show {count}",
  "collection.new": "NEW",
  "product.details": "Product details",
  "product.loadError": "Unable to load this product.",
  "product.notFound": "Product not found.",
  "product.selectSize": "Select a size",
  "product.selectOption": "Select an option",
  "product.sizeChart": "Size chart",
  "product.addToCart": "Add to cart",
  "product.adding": "Adding…",
  "product.added": "Added to cart",
  "product.buyNow": "Buy now · {price}",
  "product.giftPackaging": "Choose gift packaging",
  "product.giftWrap": "Gift wrap",
  "product.giftBox": "Gift box",
  "product.noGift": "No gift packaging",
  "product.sizeChartTitle": "Baby size chart",
  "product.sizeChartHelp": "Use height and weight for the best fit.",
  "product.size": "Size",
  "product.height": "Height",
  "product.weight": "Weight",
  "product.addWishlist": "Add to wishlist",
  "product.removeWishlist": "Remove from wishlist",
  "product.checkoutError": "Unable to start checkout.",
  "product.cartError": "Unable to add this item to your cart.",
  "cart.title": "Your cart",
  "cart.empty": "Your cart is empty",
  "cart.startShopping": "Start shopping",
  "cart.subtotal": "Subtotal",
  "cart.secureCheckout": "Secure checkout",
  "cart.applyRewardCheckout": "Apply reward & checkout",
  "cart.continueReward": "Continue with reward",
  "cart.rewardApplied": "Loyalty reward applied",
  "cart.rewardReady": "Loyalty reward ready",
  "cart.rewardConfirmed": "Shopify confirmed this reward on your cart.",
  "cart.rewardWillApply": "The app will apply this reward before checkout opens.",
  "cart.rewardCheckoutNote": "Your Shopify checkout will include the applied reward.",
  "cart.rewardPendingNote": "Your discounted total will appear after Shopify confirms the reward.",
  "cart.checkoutNote": "Shipping and taxes are calculated at checkout. Checkout may show the store’s base currency.",
  "cart.loadError": "Unable to load your cart.",
  "cart.checkoutError": "Unable to prepare checkout. Please try again.",
  "cart.rewardSignIn": "Sign in again to apply your loyalty reward.",
  "cart.rewardApplyError": "Unable to apply your loyalty reward.",
  "cart.updateError": "Unable to update this item.",
  "search.placeholder": "Search clothes, styles…",
  "search.results": "{count} RESULTS",
  "search.minimumCharacters": "Type at least 2 characters to search",
  "search.noResults": "No products matched your search",
  "wishlist.title": "My Wishlist",
  "wishlist.unavailable": "Wishlist is unavailable",
  "wishlist.disabled": "This feature is currently turned off.",
  "wishlist.savedOne": "{count} saved item",
  "wishlist.savedMany": "{count} saved items",
  "wishlist.viewProduct": "View product",
  "wishlist.empty": "Your wishlist is empty",
  "wishlist.emptyHelp": "Tap the heart on products you love and they will appear here.",
  "wishlist.remove": "Remove {product} from wishlist",
  "notifications.title": "Notifications",
  "notifications.readAll": "Read all",
  "notifications.permissionTitle": "Never miss an update",
  "notifications.permissionCopy": "Get back-in-stock alerts, order news and offers you choose.",
  "notifications.enable": "Enable",
  "notifications.enabledTitle": "Notifications enabled",
  "notifications.enabledMessage": "You can now receive store updates and offers.",
  "notifications.testTitle": "Test on this device",
  "notifications.testCopy": "Sends a local notification immediately.",
  "notifications.sendTest": "Send test",
  "notifications.empty": "Nothing new yet",
  "notifications.emptyHelp": "Messages from Carter's will appear here.",
  "notifications.clearHistory": "Clear notification history",
  "notifications.testNotificationTitle": "Carter's test notification",
  "notifications.testNotificationBody": "Notifications are working on this device 🎉",
  "notifications.webUnavailable": "Test notifications are available in the Android and iOS app.",
  "notifications.permissionDenied": "Notification permission was not granted.",
  "notifications.enableError": "Unable to enable notifications.",
  "notifications.testError": "Unable to create test notification.",
  "notifications.physicalDevice": "Push notifications require a physical device or supported simulator.",
  "notifications.productionNotConfigured": "Push notifications are not configured for this production build.",
  "notifications.deviceSaveError": "The admin server could not save this device.",
  "notifications.channelName": "Store updates",
  "account.title": "Carter's Account",
  "account.profile": "Profile",
  "account.rewards": "Rewards",
  "account.addresses": "Addresses",
  "account.orders": "Orders",
  "account.savedAddresses": "Saved addresses",
  "account.savedAddressesHelp": "Manage delivery details and choose your default address.",
  "account.orderHistory": "Order history",
  "account.orderHistoryHelp": "Review your purchases, payment status, and delivery progress.",
  "account.personalDetails": "Personal details",
  "account.personalDetailsHelp": "Keep your contact information accurate for orders and delivery.",
  "account.passwordSecurity": "Password & security",
  "account.passwordSecurityHelp": "Create a new password, or leave both fields empty to keep the current one.",
  "account.newPassword": "New password",
  "account.confirmPassword": "Confirm new password",
  "account.saveChanges": "Save changes",
  "account.order": "Order {name}",
  "account.quantity": "Quantity: {count}",
  "account.statusPending": "Pending",
  "account.statusPaid": "Paid",
  "account.statusAuthorized": "Authorized",
  "account.statusRefunded": "Refunded",
  "account.statusPartiallyPaid": "Partially paid",
  "account.statusPartiallyRefunded": "Partially refunded",
  "account.statusVoided": "Voided",
  "account.statusFulfilled": "Fulfilled",
  "account.statusUnfulfilled": "Unfulfilled",
  "account.statusPartial": "Partially fulfilled",
  "account.statusRestocked": "Restocked",
  "account.statusScheduled": "Scheduled",
  "account.statusOnHold": "On hold",
  "account.myAccount": "MY CARTER'S ACCOUNT",
  "account.hello": "Hello, {name}",
  "account.default": "DEFAULT",
  "account.edit": "Edit",
  "account.makeDefault": "Make default",
  "account.noAddress": "You do not have a saved address yet.",
  "account.addAddress": "Add an address",
  "account.viewOrder": "View order details",
  "account.noOrders": "You have not placed an order yet.",
  "account.signOut": "Sign out",
  "account.continueShopping": "Continue shopping",
  "account.signIn": "Sign in",
  "account.createAccount": "Create account",
  "account.resetPassword": "Reset your password",
  "account.welcomeBack": "Welcome back",
  "account.customerAccount": "CARTER'S CUSTOMER ACCOUNT",
  "account.resetHelp": "Enter your email and Shopify will send you a secure password-reset link.",
  "account.signInHelp": "Sign in for faster checkout, saved addresses, rewards, and order history.",
  "account.firstName": "First name",
  "account.lastName": "Last name",
  "account.email": "Email address",
  "account.phone": "Phone number",
  "account.password": "Password",
  "account.backToSignIn": "Back to sign in",
  "account.forgotPassword": "Forgot password?",
  "account.sendReset": "Send reset link",
  "account.secureShopify": "Your account is securely managed through Carter's Shopify store.",
  "account.addressDetails": "Address details",
  "account.address": "Address",
  "account.address2": "Apartment, suite, etc. (optional)",
  "account.city": "City",
  "account.province": "Province",
  "account.postalCode": "Postal code",
  "account.country": "Country",
  "account.phoneShort": "Phone",
  "account.saveAddress": "Save address",
  "account.backOrders": "Back to orders",
  "account.placedOn": "Placed on {date}",
  "account.payment": "Payment",
  "account.delivery": "Delivery",
  "account.items": "Items",
  "account.orderTotal": "Order total",
  "account.loadingRewards": "Loading your rewards account…",
  "account.rewardsUnavailable": "Rewards are temporarily unavailable",
  "account.rewardsConnectionError": "We could not connect to the rewards service.",
  "account.pointsAvailable": "points available · up to {value} {currency} value",
  "account.lifetimeEarned": "lifetime earned",
  "account.customer": "Carter’s Customer",
  "account.earnEveryItem": "Earn on every item",
  "account.secureRedemption": "Secure redemption",
  "account.privateCodes": "Private codes",
  "account.activeRewards": "Active rewards",
  "account.available": "{count} available",
  "account.howRewardsWork": "How rewards work",
  "account.redeemPoints": "Redeem your points",
  "account.pointsActivity": "Points activity",
  "account.noRewardActivity": "No reward activity yet. Your first paid order will start your balance.",
  "account.viewOrderAccessibility": "View order {name}",
  "account.rewardsTier": "REWARDS {tier}",
  "account.pointsToReward": "{count} points to your first reward",
  "account.rewardReady": "You have a reward ready",
  "account.keepShoppingReward": "Keep shopping to unlock your first checkout discount.",
  "account.redeemFrom": "Redeem from {count} points whenever you are ready.",
  "account.newRewardReady": "NEW REWARD · READY TO USE",
  "account.rewardOffExpires": "{amount} {currency} off · expires {date}",
  "account.rewardOffReady": "{amount} {currency} off · ready to use",
  "account.rewardStepAdd": "1. Add products to your bag.",
  "account.rewardStepApply": "2. Tap Apply reward & checkout.",
  "account.rewardStepCheckout": "3. Your reward appears automatically in Shopify checkout.",
  "account.reward": "Reward",
  "account.useAllRewards": "Use all rewards together",
  "account.combineRewardsHelp": "Shopify cannot stack overlapping product rewards. Combine them into one checkout code with the full value.",
  "account.combining": "Combining…",
  "account.combineRewards": "Combine rewards",
  "account.shopSignedIn": "Shop signed in",
  "account.shopSignedInHelp": "Buy products using this same Shopify customer account.",
  "account.earnAutomatically": "Earn automatically",
  "account.earnAutomaticallyHelp": "{count} points for every product, added after payment is confirmed.",
  "account.saveAtCheckout": "Save at checkout",
  "account.saveAtCheckoutHelp": "Redeem points here and your private code is applied automatically at checkout.",
  "account.chooseCheckoutReward": "Choose a checkout reward",
  "account.pointsRate": "{count} points = 1 {currency}",
  "account.customPoints": "Or enter a custom point amount",
  "account.minimumPoints": "{count} points or more",
  "account.rewardValue": "Reward value",
  "account.creatingReward": "Creating secure reward…",
  "account.createReward": "Create checkout reward",
  "account.needMorePoints": "You need {count} more points to unlock redemption.",
  "account.choosePointBlocks": "Choose at least {minimum} points, in blocks of {block}, without exceeding your balance.",
  "account.rewardValidity": "Your code is private, single-use, and valid for {days} days.",
  "account.redemptionPaused": "Reward redemption is temporarily paused. Your points remain safely in your account.",
  "account.checkoutReward": "Checkout reward",
  "account.expires": "Expires {date}",
  "account.rewardTerms": "Points are added after payment confirmation. Cancelled or returned orders may reverse earned points. Reward codes cannot be exchanged for cash and may be subject to Shopify discount-combination rules.",
  "account.validEmail": "Enter a valid email address.",
  "account.resetSent": "Shopify sent a password-reset link to your email. Please check your inbox and spam folder.",
  "account.resetSendError": "We could not send the reset email right now.",
  "account.completeFields": "Please complete every field. Password must contain at least 5 characters.",
  "account.accessError": "Unable to access your Shopify account.",
  "account.passwordMismatch": "Passwords must match and contain at least 5 characters.",
  "account.profileUpdated": "Your account details were updated.",
  "account.profileUpdateError": "Unable to update your profile.",
  "account.minimumRedemption": "Redeem at least {count} whole points.",
  "account.rewardCreated": "{count} points redeemed. Reward {code} will apply automatically at checkout.",
  "account.rewardCreateError": "Unable to create your reward.",
  "account.rewardsCombined": "{count} rewards combined into {code}.",
  "account.rewardsCombineError": "Unable to combine rewards.",
  "account.addressRequired": "Please complete the name, address, city, and country.",
  "account.addressSaved": "Your address was saved.",
  "account.addressSaveError": "Unable to save this address.",
  "account.defaultAddressUpdated": "Your default address was updated.",
  "account.defaultAddressError": "Unable to update the default address.",
  "account.signInAgain": "Please sign in again.",
  "account.sessionExpired": "Your session expired. Please sign in again.",
  "app.maintenance": "MAINTENANCE",
  "app.updateRequired": "UPDATE REQUIRED",
  "app.backSoon": "We’ll be right back",
  "app.updateApp": "Please update the app",
  "app.maintenanceMessage": "We’re making a few improvements to your shopping experience. Please try again shortly.",
  "app.updateNow": "Update now",
  "app.checkAgain": "Check again",
  "app.version": "Installed {installed} · Required {required}",
  "errors.network": "Please check your connection and try again.",
} as const;

export type TranslationKey = keyof typeof en;
