import { useNotifications } from "@/components/notification-context";
import { Ionicons } from "@expo/vector-icons";
import { Stack, useRouter } from "expo-router";
import { useState } from "react";
import { ActivityIndicator, Alert, Linking, Platform, SafeAreaView, ScrollView, StyleSheet, Text, TouchableOpacity, View } from "react-native";
import * as ExpoNotifications from "expo-notifications";
import { useLocalization } from "@/components/localization-context";
import { hasArabicText } from "@/services/locale";

export default function NotificationsScreen(){
  const {t,formatDate,isArabic}=useLocalization();
  const router=useRouter(); const {items,enabled,registering,register,markAllRead,clear,openItem}=useNotifications(); const [error,setError]=useState("");
  const enable=async()=>{try{setError("");await register();Alert.alert(t("notifications.enabledTitle"),t("notifications.enabledMessage"));}catch(e){setError(e instanceof Error?e.message:t("notifications.enableError"))}};
  const sendTest=async()=>{try{if(Platform.OS==="web")throw new Error(t("notifications.webUnavailable"));const permission=await ExpoNotifications.requestPermissionsAsync();if(permission.status!=="granted")throw new Error(t("notifications.permissionDenied"));await ExpoNotifications.scheduleNotificationAsync({content:{title:t("notifications.testNotificationTitle"),body:t("notifications.testNotificationBody"),data:{url:"/notifications"}},trigger:null});}catch(e){setError(e instanceof Error?e.message:t("notifications.testError"))}};
  const open=async(id:string)=>{const item=await openItem(id);if(item?.url?.startsWith("/"))router.push(item.url as never);else if(item?.url&&/^https:\/\//i.test(item.url))await Linking.openURL(item.url)};
  return <SafeAreaView style={styles.screen}><Stack.Screen options={{headerShown:false}}/><View style={styles.header}><TouchableOpacity onPress={()=>router.back()} style={styles.icon}><Ionicons name="arrow-back" size={24} color="#0b2944"/></TouchableOpacity><Text style={styles.title}>{t("notifications.title")}</Text><TouchableOpacity onPress={markAllRead}><Text style={styles.action}>{t("notifications.readAll")}</Text></TouchableOpacity></View>{!enabled&&<View style={styles.permission}><View style={styles.bell}><Ionicons name="notifications" size={28} color="#397ab5"/></View><View style={styles.permissionCopy}><Text style={styles.permissionTitle}>{t("notifications.permissionTitle")}</Text><Text style={[styles.copy,isArabic&&styles.arabicParagraph]}>{t("notifications.permissionCopy")}</Text></View><TouchableOpacity style={styles.enable} onPress={enable} disabled={registering}>{registering?<ActivityIndicator color="#fff"/>:<Text style={styles.enableText}>{t("notifications.enable")}</Text>}</TouchableOpacity></View>}{error?<Text style={styles.error}>{error}</Text>:null}<View style={styles.testBox}><View><Text style={styles.permissionTitle}>{t("notifications.testTitle")}</Text><Text style={[styles.copy,isArabic&&styles.arabicParagraph]}>{t("notifications.testCopy")}</Text></View><TouchableOpacity style={styles.testButton} onPress={sendTest}><Text style={styles.testButtonText}>{t("notifications.sendTest")}</Text></TouchableOpacity></View><ScrollView contentContainerStyle={styles.content}>{items.length?items.map(item=><TouchableOpacity key={item.id} style={[styles.item,!item.read&&styles.unread]} onPress={()=>open(item.id)}><View style={styles.itemIcon}><Ionicons name="sparkles-outline" size={20} color="#397ab5"/></View><View style={styles.itemCopy}><Text style={[styles.itemTitle,hasArabicText(item.title)&&styles.arabicText]}>{item.title}</Text><Text style={[styles.body,hasArabicText(item.body)&&styles.arabicParagraph]}>{item.body}</Text><Text style={styles.date}>{formatDate(item.receivedAt,{dateStyle:"medium",timeStyle:"short"})}</Text></View>{!item.read&&<View style={styles.dot}/>}</TouchableOpacity>):<View style={styles.empty}><Ionicons name="notifications-off-outline" size={44} color="#a8b7c3"/><Text style={styles.emptyTitle}>{t("notifications.empty")}</Text><Text style={[styles.copy,isArabic&&styles.arabicParagraph]}>{t("notifications.emptyHelp")}</Text></View>}{items.length>0&&<TouchableOpacity onPress={clear}><Text style={styles.clear}>{t("notifications.clearHistory")}</Text></TouchableOpacity>}</ScrollView></SafeAreaView>
}
const styles=StyleSheet.create({screen:{flex:1,backgroundColor:"#f7f8fa"},arabicText:{writingDirection:"rtl"},arabicParagraph:{writingDirection:"rtl",textAlign:"right"},header:{height:58,backgroundColor:"#fff",borderBottomWidth:1,borderBottomColor:"#e5e9ed",flexDirection:"row",alignItems:"center",justifyContent:"space-between",paddingHorizontal:13},icon:{width:40,height:40,alignItems:"center",justifyContent:"center"},title:{fontSize:17,fontWeight:"900",color:"#0b2944"},action:{color:"#397ab5",fontSize:12,fontWeight:"800"},permission:{margin:15,padding:15,borderRadius:12,backgroundColor:"#eaf3f9",flexDirection:"row",alignItems:"center",gap:11},bell:{width:44,height:44,borderRadius:22,backgroundColor:"#fff",alignItems:"center",justifyContent:"center"},permissionCopy:{flex:1},permissionTitle:{fontSize:13,fontWeight:"900",color:"#0b2944"},copy:{fontSize:11,lineHeight:16,color:"#6f7c89",marginTop:3},enable:{minWidth:68,height:36,paddingHorizontal:10,borderRadius:7,backgroundColor:"#397ab5",alignItems:"center",justifyContent:"center"},enableText:{color:"#fff",fontSize:11,fontWeight:"900"},error:{color:"#b64f4f",fontSize:11,textAlign:"center",marginHorizontal:20},testBox:{marginHorizontal:15,marginTop:10,padding:14,borderRadius:10,backgroundColor:"#fff",borderWidth:1,borderColor:"#e1e7eb",flexDirection:"row",alignItems:"center",justifyContent:"space-between"},testButton:{backgroundColor:"#0b2944",borderRadius:7,paddingHorizontal:14,paddingVertical:10},testButtonText:{color:"#fff",fontSize:11,fontWeight:"900"},content:{padding:15,gap:9},item:{padding:14,backgroundColor:"#fff",borderRadius:10,flexDirection:"row",gap:12,borderWidth:1,borderColor:"#e7ebee"},unread:{backgroundColor:"#f0f7fc",borderColor:"#c9ddeb"},itemIcon:{width:37,height:37,borderRadius:19,backgroundColor:"#e6f0f7",alignItems:"center",justifyContent:"center"},itemCopy:{flex:1},itemTitle:{fontSize:13,fontWeight:"900",color:"#0b2944"},body:{fontSize:11,lineHeight:17,color:"#52616d",marginTop:4},date:{fontSize:9,color:"#98a3ac",marginTop:7,writingDirection:"ltr"},dot:{width:7,height:7,borderRadius:4,backgroundColor:"#397ab5",marginTop:5},empty:{alignItems:"center",paddingVertical:90},emptyTitle:{fontSize:16,fontWeight:"900",color:"#0b2944",marginTop:14},clear:{textAlign:"center",color:"#b55252",fontSize:11,fontWeight:"700",padding:15}});
