import { NextResponse } from "next/server";
import { findLoyaltyAccount, loyaltySnapshot, mergeActiveLoyaltyRewards, redeemLoyaltyPoints } from "@/lib/loyalty";
import { createShopifyLoyaltyDiscount, mergeShopifyLoyaltyDiscounts } from "@/lib/loyalty-shopify";
import { findActiveCustomerBlock } from "@/lib/customer-blocks";

const cors={"Access-Control-Allow-Origin":"*","Access-Control-Allow-Headers":"Content-Type"};
export async function POST(request:Request){const body=await request.json().catch(()=>null);const customerAccessToken=typeof body?.customerAccessToken==="string"?body.customerAccessToken.trim():"";if(!customerAccessToken)return NextResponse.json({error:"Customer session required."},{status:401,headers:cors});try{const customer=await verifyCustomer(customerAccessToken);if(!customer)return NextResponse.json({error:"Customer session expired."},{status:401,headers:cors});if(await findActiveCustomerBlock({customerId:customer.id,email:customer.email}))return NextResponse.json({error:"This customer account is restricted. Contact customer support for assistance."},{status:403,headers:cors});if(body?.action==="redeem"){const result=await redeemLoyaltyPoints({customerId:customer.id,email:customer.email,points:Number(body.points)},createShopifyLoyaltyDiscount);return NextResponse.json(result,{headers:cors})}if(body?.action==="merge")return NextResponse.json(await mergeActiveLoyaltyRewards({customerId:customer.id,email:customer.email},mergeShopifyLoyaltyDiscounts),{headers:cors});const [account,snapshot]=await Promise.all([findLoyaltyAccount(customer.id,customer.email),loyaltySnapshot()]);return NextResponse.json({programName:snapshot.settings.programName,enabled:snapshot.settings.enabled,points:account?.points||0,lifetimePoints:account?.lifetimePoints||0,pointsPerItem:snapshot.settings.pointsPerItem,pointsPerCurrencyUnit:snapshot.settings.pointsPerCurrencyUnit,minimumRedemptionPoints:snapshot.settings.minimumRedemptionPoints,rewardExpiryDays:snapshot.settings.rewardExpiryDays,silverTierPoints:snapshot.settings.silverTierPoints,goldTierPoints:snapshot.settings.goldTierPoints,vipTierPoints:snapshot.settings.vipTierPoints,currencyCode:customer.currencyCode,transactions:snapshot.transactions.filter(transaction=>transaction.accountId===account?.id).slice(0,20)},{headers:cors})}catch(error){return NextResponse.json({error:error instanceof Error?error.message:"Loyalty is unavailable."},{status:400,headers:cors})}}
export async function OPTIONS(){return new NextResponse(null,{status:204,headers:cors})}

async function verifyCustomer(customerAccessToken:string){const domain=(process.env.SHOPIFY_ADMIN_DOMAIN||process.env.SHOPIFY_DOMAIN||process.env.NEXT_PUBLIC_SHOPIFY_DOMAIN||"").replace(/^https?:\/\//,"").replace(/\/$/,"");const token=process.env.SHOPIFY_STOREFRONT_ACCESS_TOKEN||process.env.SHOPIFY_TOKEN||process.env.NEXT_PUBLIC_SHOPIFY_STOREFRONT_ACCESS_TOKEN||"";const version=process.env.SHOPIFY_STOREFRONT_API_VERSION||process.env.SHOPIFY_API_VERSION||"2025-10";if(!domain||!token)throw new Error("Shopify Storefront verification is not configured.");const response=await fetch(`https://${domain}/api/${version}/graphql.json`,{method:"POST",headers:{"Content-Type":"application/json","X-Shopify-Storefront-Access-Token":token},body:JSON.stringify({query:`query loyaltyCustomer($token:String!){customer(customerAccessToken:$token){id email}shop{paymentSettings{currencyCode}}}`,variables:{token:customerAccessToken}}),cache:"no-store"});const payload=await response.json().catch(()=>null);if(!response.ok||payload?.errors?.length)throw new Error("Unable to verify the Shopify customer.");const customer=payload?.data?.customer as {id:string;email:string}|null;return customer?{...customer,currencyCode:String(payload?.data?.shop?.paymentSettings?.currencyCode||"USD")}:null}
